"""Check the declared-sample cubes that phase 3's job list could not see.

check_pass.py builds its job list ONCE, at startup, and drops any sampled cube
whose proof is not on disk at that moment ("pruned by policy"). Cube 448's
proof was regenerated by hand at 2026-08-23 01:14:52 - twelve minutes AFTER
check_pass fixed its list at 01:02:56 - so that pass will never check it, and
phase 3 will report success with 1,599 of the declared 1,600 verified without
anything saying so.

This closes the gap using check_pass.check_one itself, NOT a reimplementation:
same scratch paths, same sha-against-the-solve-time-hash comparison, same
drat-trim invocation, same transcript row shape. A second implementation could
verify a proof the real checker would have rejected.

Run it only when phase 3 has returned. Safe to re-run: cubes already in
transcripts.jsonl are skipped, and it appends nothing on failure.

Usage: close_sample_gap.py <wavedir> [--apply]
       (default is a dry run; --apply appends the transcript lines)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import check_pass  # noqa: E402
import verdict_io  # noqa: E402


def main():
    wavedir = sys.argv[1] if len(sys.argv) > 1 else "wave274tot"
    apply = "--apply" in sys.argv
    w = os.path.join(HERE, wavedir)
    trans = os.path.join(w, "transcripts.jsonl")

    with open(os.path.join(w, "sample.json"), encoding="ascii") as fh:
        declared = set(int(x) for x in json.load(fh)["cubes"])

    verified = set()
    if os.path.exists(trans):
        with open(trans, encoding="ascii") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        verified.add(json.loads(line)["cube"])
                    except Exception:  # noqa: BLE001
                        pass

    gap = sorted(declared - verified)
    print(f"declared sample: {len(declared)}   verified: "
          f"{len(declared & verified)}   gap: {len(gap)}")
    if not gap:
        print("NOTHING TO DO: the declared sample is complete.")
        return 0
    print(f"gap cubes: {gap}")

    todo = []
    for c in gap:
        v = verdict_io.read_verdict(os.path.join(w, "verdicts",
                                                 f"v{c:05d}.json"))
        if v is None:
            print(f"  cube {c}: NO READABLE VERDICT - skipping, nothing to "
                  f"check against")
            continue
        if v.get("rc") != 20:
            print(f"  cube {c}: verdict rc={v.get('rc')}, not 20 - skipping")
            continue
        if "drat_sha256" not in v:
            print(f"  cube {c}: verdict has no drat_sha256 - skipping")
            continue
        gz = os.path.join(w, "drat", f"cube_{c:05d}.drat.gz")
        raw = os.path.join(w, "drat", f"cube_{c:05d}.drat")
        if not (os.path.exists(gz) or os.path.exists(raw)):
            print(f"  cube {c}: proof genuinely absent - CANNOT check "
                  f"(its digest stands in pruned.jsonl)")
            continue
        sz = os.path.getsize(raw if os.path.exists(raw) else gz)
        todo.append((wavedir, c, v["lits"], v["drat_sha256"]))
        print(f"  cube {c}: checkable, proof {sz:,} bytes")

    if not todo:
        print("nothing checkable.")
        return 0
    if not apply:
        print(f"\nDRY RUN: would check {len(todo)} cube(s). "
              f"Re-run with --apply.")
        return 0

    ok = fail = 0
    for job in todo:
        c = job[1]
        print(f"\nchecking cube {c} ...", flush=True)
        r = check_pass.check_one(job)
        if r.get("ok"):
            with open(trans, "a", encoding="ascii", newline="\n") as fh:
                fh.write(json.dumps(r) + "\n")
            ok += 1
            print(f"  cube {c}: {r['verdict']} in "
                  f"{r.get('check_wall_s')}s - transcript line appended")
        else:
            fail += 1
            # Deliberately NOT written to CHECK_FAILURES.jsonl: that file halts
            # the campaign and stops the watchdog, and this script is a manual
            # gap-closer run outside the orchestrator. Report it and let a
            # human decide.
            print(f"  cube {c}: NOT VERIFIED -> "
                  f"{r.get('error', r.get('verdict'))}")
            print("  !! This is a real check failure. Do NOT ignore it.")
    print(f"\ndone: {ok} verified, {fail} failed")
    return 1 if fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
